apiVersion: v2
appVersion: 1.1.0
description: Custom Prom-Grafana
kubeVersion: '>=v1.25'
name: kube-prometheus-stack
version: 1.4.0
dependencies:
  - name: kube-prometheus-stack
    version: 1.4.0
    repository: oci://registry-1.docker.io/highball
  - name: loki
    version: 1.1.0
    repository: oci://registry-1.docker.io/highball
  - name: "promtail"
    condition: promtail.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^6.7.4"
  - name: "tempo"
    repository: "https://grafana.github.io/helm-charts"
    version: "1.10.3"