apiVersion: v2
appVersion: 1.1.0
description: Custom Prom-Grafana
kubeVersion: '>=v1.25'
name: Custom Prom-Grafana
version: 1.4.0
dependencies:
  - name: kube-prometheus-stack
    version: 72.0.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    version: 3.5.0
    repository: https://grafana.github.io/helm-charts
  - name: "promtail"
    condition: promtail.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^6.7.4"
  - name: "tempo"
    repository: "https://grafana.github.io/helm-charts"
    version: "1.10.3"
  - name: opentelemetry-collector
    version: 0.122.5
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts